image: "scorpil/rust:stable"

stages:
  - build

cache:
  key: "$CI_JOB_NAME"

before_script:
  - set -e
  - apt-get -qq update
  - apt-get -qq -y install build-essential curl git libudev-dev pkg-config
  - export PATH="/root/.cargo/bin:$PATH"
  - sh ci/install.sh

after_script:
  - set +e

variables:
  TRAVIS_OS_NAME: "linux"

i686_unknown_linux_gnu:
  script:
  - bash ci/script.sh
  stage: build
  variables:
    TARGET: "i686-unknown-linux-gnu"

i686_unknown_linux_musl:
  script:
  - bash ci/script.sh
  stage: build
  variables:
    TARGET: "i686-unknown-linux-musl"

i686_unknown_freebsd:
  script:
  - bash ci/script.sh
  stage: build
  variables:
    TARGET: "i686-unknown-freebsd"

mipsel_unknown_linux_gnu:
  script:
  - bash ci/script.sh
  stage: build
  variables:
    TARGET: "mipsel-unknown-linux-gnu"
