[package]
name = "serialport"
version = "1.0.2-pre"
authors = ["Bryant Mairs <bryant@mai.rs>"]
categories = ["hardware-support"]
keywords = ["serial", "hardware", "system", "RS232"]
license = "MPL-2.0"
readme = "README.asciidoc"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"

[badges]
gitlab = { repository = "susurrus/serialport-rs" }
appveyor = { repository = "Susurrus/serialport-rs", service = "gitlab" }

[dev-dependencies]
argparse = "0.2"

[dependencies]
libc = { path = "../libc" }

[target."cfg(unix)".dependencies]
ioctl-rs = "0.1.5"
nix = { path = "../nix" }

[target.'cfg(target_os = "linux")'.dependencies]
libudev = "0.2.0"

[target."cfg(windows)".dependencies]
kernel32-sys = "0.2"
winapi = "0.2"
winreg = "0.4"
